/**
 * download.ts
 *
 * Unified download helper that works in both browser and Median webview.
 *
 * Median's webview doesn't intercept blob-URL downloads (jsPDF doc.save /
 * XLSX.writeFile both create a hidden <a> with a blob href — the webview
 * ignores the click). Instead we must call median.downloadFile() with a
 * real https:// URL.
 *
 * Strategy for Median:
 *   1. Convert the file to a Blob.
 *   2. Upload it to Supabase Storage (temp-downloads bucket) with a short TTL path.
 *   3. Create a signed URL (60 s is plenty for the native download manager).
 *   4. Pass that URL to median.downloadFile().
 *   5. Clean up the remote file after a short delay.
 */

import { supabase } from "@/integrations/supabase/client";

function isMedian(): boolean {
  return !!(window as any).median || !!(window as any).gonative;
}

/** Upload a Blob to Supabase Storage and return a short-lived signed URL. */
async function uploadAndSign(blob: Blob, filename: string): Promise<string> {
  const path = `temp/${Date.now()}_${filename}`;

  const { error: upErr } = await supabase.storage
    .from("temp-downloads")
    .upload(path, blob, {
      contentType: blob.type,
      upsert: true,
    });

  if (upErr) throw new Error(`Upload failed: ${upErr.message}`);

  const { data, error: signErr } = await supabase.storage
    .from("temp-downloads")
    .createSignedUrl(path, 120); // 2-minute window

  if (signErr || !data?.signedUrl)
    throw new Error(`Signed URL failed: ${signErr?.message}`);

  // Fire-and-forget cleanup after 3 minutes
  setTimeout(() => {
    supabase.storage.from("temp-downloads").remove([path]).catch(() => {});
  }, 3 * 60 * 1000);

  return data.signedUrl;
}

/**
 * Download a PDF generated by jsPDF.
 * Pass the jsPDF doc instance and the desired filename (without path).
 */
export async function savePDF(doc: any, filename: string): Promise<void> {
  if (isMedian()) {
    const blob: Blob = doc.output("blob");
    const url = await uploadAndSign(blob, filename);
    (window as any).median.downloadFile({ url, filename });
  } else {
    doc.save(filename);
  }
}

/**
 * Download an XLSX workbook generated by SheetJS.
 * Pass the workbook object and desired filename (without path).
 */
export async function saveXLSX(
  XLSX: any,
  wb: any,
  filename: string
): Promise<void> {
  if (isMedian()) {
    const buf: ArrayBuffer = XLSX.write(wb, {
      bookType: "xlsx",
      type: "array",
    });
    const blob = new Blob([buf], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    });
    const url = await uploadAndSign(blob, filename);
    (window as any).median.downloadFile({ url, filename });
  } else {
    XLSX.writeFile(wb, filename);
  }
}
