/**
 * download.ts
 *
 * Unified download helper that works in browser, Median webview, and
 * mobile browsers (iOS Safari / Android Chrome) where blob-URL clicks
 * are silently blocked.
 *
 * Strategy:
 *   - Median app  → median.downloadFile() with a signed Supabase URL
 *   - Mobile browser (non-Median) → same upload+sign strategy, then
 *     window.open() the signed URL (works on iOS Safari & Android Chrome)
 *   - Desktop browser → standard doc.save() / XLSX.writeFile() blob approach
 */

import { supabase } from "@/integrations/supabase/client";

function isMedian(): boolean {
  return !!(window as any).median || !!(window as any).gonative;
}

function isMobileBrowser(): boolean {
  return /android|iphone|ipad|ipod/i.test(navigator.userAgent);
}

/** Upload a Blob to Supabase Storage and return a short-lived signed URL. */
async function uploadAndSign(blob: Blob, filename: string): Promise<string> {
  const path = `temp/${Date.now()}_${filename}`;

  const { error: upErr } = await supabase.storage
    .from("temp-downloads")
    .upload(path, blob, {
      contentType: blob.type,
      upsert: true,
    });

  if (upErr) throw new Error(`Upload failed: ${upErr.message}`);

  const { data, error: signErr } = await supabase.storage
    .from("temp-downloads")
    .createSignedUrl(path, 120); // 2-minute window

  if (signErr || !data?.signedUrl)
    throw new Error(`Signed URL failed: ${signErr?.message}`);

  // Fire-and-forget cleanup after 3 minutes
  setTimeout(() => {
    supabase.storage.from("temp-downloads").remove([path]).catch(() => {});
  }, 3 * 60 * 1000);

  return data.signedUrl;
}

/**
 * Download a PDF generated by jsPDF.
 * Pass the jsPDF doc instance and the desired filename (without path).
 */
export async function savePDF(doc: any, filename: string): Promise<void> {
  if (isMedian()) {
    const blob: Blob = doc.output("blob");
    const url = await uploadAndSign(blob, filename);
    (window as any).median.downloadFile({ url, filename });
  } else if (isMobileBrowser()) {
    // iOS Safari / Android Chrome block blob-URL clicks — use signed URL + window.open
    const blob: Blob = doc.output("blob");
    const url = await uploadAndSign(blob, filename);
    window.open(url, "_blank");
  } else {
    doc.save(filename);
  }
}

/**
 * Download an XLSX workbook generated by SheetJS.
 * Pass the workbook object and desired filename (without path).
 */
export async function saveXLSX(
  XLSX: any,
  wb: any,
  filename: string
): Promise<void> {
  if (isMedian()) {
    const buf: ArrayBuffer = XLSX.write(wb, {
      bookType: "xlsx",
      type: "array",
    });
    const blob = new Blob([buf], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    });
    const url = await uploadAndSign(blob, filename);
    (window as any).median.downloadFile({ url, filename });
  } else if (isMobileBrowser()) {
    // iOS Safari / Android Chrome — use signed URL + window.open
    const buf: ArrayBuffer = XLSX.write(wb, {
      bookType: "xlsx",
      type: "array",
    });
    const blob = new Blob([buf], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    });
    const url = await uploadAndSign(blob, filename);
    window.open(url, "_blank");
  } else {
    XLSX.writeFile(wb, filename);
  }
}

/**
 * Download any blob (e.g. ZIP) on all platforms.
 * Use this instead of a raw <a>.click() in mobile-facing code.
 */
export async function saveBlob(
  blob: Blob,
  filename: string
): Promise<void> {
  if (isMedian()) {
    const url = await uploadAndSign(blob, filename);
    (window as any).median.downloadFile({ url, filename });
  } else if (isMobileBrowser()) {
    const url = await uploadAndSign(blob, filename);
    window.open(url, "_blank");
  } else {
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = filename;
    a.click();
    URL.revokeObjectURL(a.href);
  }
}

/**
 * Open a signed/remote URL as a download on all platforms.
 * Use this instead of a raw <a>.click() when you already have an https:// URL.
 */
export function saveRemoteUrl(url: string, filename: string): void {
  if (isMedian()) {
    (window as any).median.downloadFile({ url, filename });
  } else {
    // Works on mobile browsers too — signed https URL, not a blob
    window.open(url, "_blank");
  }
}
