/**
 * download.ts
 *
 * Unified download helper that works in both browser and Median webview.
 *
 * Median's webview doesn't intercept blob-URL downloads (jsPDF doc.save /
 * XLSX.writeFile both create a hidden <a> with a blob href — the webview
 * ignores the click). Instead we must call median.downloadFile() with a
 * base64 data URI, which routes the file through Median's native download
 * manager and saves it to the phone's Downloads folder.
 */

function isMedian(): boolean {
  return !!(window as any).median || !!(window as any).gonative;
}

/**
 * Download a PDF generated by jsPDF.
 * Pass the jsPDF doc instance and the desired filename (without path).
 */
export function savePDF(doc: any, filename: string): void {
  if (isMedian()) {
    // jsPDF can output a base64 string directly
    const base64 = doc.output("datauristring"); // "data:application/pdf;base64,..."
    (window as any).median.downloadFile({
      url: base64,
      filename,
    });
  } else {
    doc.save(filename);
  }
}

/**
 * Download an XLSX workbook generated by SheetJS.
 * Pass the workbook object and desired filename (without path).
 */
export function saveXLSX(XLSX: any, wb: any, filename: string): void {
  if (isMedian()) {
    // SheetJS can write to a base64 string
    const base64 = XLSX.write(wb, { bookType: "xlsx", type: "base64" });
    const dataUri = `data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,${base64}`;
    (window as any).median.downloadFile({
      url: dataUri,
      filename,
    });
  } else {
    XLSX.writeFile(wb, filename);
  }
}
