// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Cache the token in memory for the duration of the JS session.
// getSession() on the Supabase client re-reads from localStorage and can
// trigger a token refresh if the token is expired — calling it on every
// serverFn (there are many) causes a flood of refresh requests and 429s.
let _cachedToken: string | null = null;
let _cacheExpiry = 0;

async function getAccessToken(): Promise<string | null> {
  const now = Date.now();
  // Return cached token if still valid (with 60s buffer before expiry)
  if (_cachedToken && _cacheExpiry - 60_000 > now) {
    return _cachedToken;
  }
  const { data } = await supabase.auth.getSession();
  if (!data.session) {
    _cachedToken = null;
    _cacheExpiry = 0;
    return null;
  }
  _cachedToken = data.session.access_token;
  // Supabase tokens expire in 3600s; store the expiry from the session
  _cacheExpiry = (data.session.expires_at ?? 0) * 1000;
  return _cachedToken;
}

// Listen for auth state changes to invalidate the cache immediately
supabase.auth.onAuthStateChange((_event, session) => {
  if (session) {
    _cachedToken = session.access_token;
    _cacheExpiry = (session.expires_at ?? 0) * 1000;
  } else {
    _cachedToken = null;
    _cacheExpiry = 0;
  }
});

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const token = await getAccessToken();
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
